version: '1.0.{build}'
image: Ubuntu
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./MUD.sln --verbosity m
build:
  project: MUD.sln
  publish_nuget: true
  publish_aspnet_core: true
  publish_core_console: true
  verbosity: minimal
after_build:
  # For once the build has completed
artifacts:
 - path: '\MUD.Main\bin\Debug\netcoreapp3.1\publish'
   name: MUD
   type: Zip # maybe nuget?
clone_depth: 1
#test_script:
  # restore packages for our unit tests
#  - cmd: dotnet restore ./tests/tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
#  - cmd: cd tests
#  - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off
